### ISSUE TITLE
Add services and data models for api resources

### ISSUE THREAD

**Issue by ethanmassie** [ethanmassie/wanikani-api-ng#1]
The resources can be found [here](https://docs.api.wanikani.com/20170710/#resources).

Comment which resource you intend to work on and submit a pull requests with a message explaining which resource you completed.

- [X] Assignments
- [x] Level Progressions
- [x] Resets
- [x] Reviews
- [x] Review Statistics
- [x] SRS Stages
- [x] Study Materials
- [x] Subjects
- [x] Summary
- [x] User
- [x] Voice Actors

**Comment by jwetzell** [comment]
I'll work backwards and can start with Voice Actors

**Comment by ethanmassie** [comment]
> I'll work backwards and can start with Voice Actors

@jwetzell sounds good. Make pull requests as you complete individual resources.

**Comment by jwetzell** [comment]
You know I'll take that sweet sweet User resource next

**Comment by jwetzell** [comment]
Working on SRS Stages

**Comment by ethanmassie** [comment]
I'm thinking that we might want to change our data models a bit.  I don't know if it is necessary, but we might want to add a <resource>-data model. I.e for assignments we would have assignments.model, assignments-data.model, and assignments-collection.model. This way we don't have the type for assignments data defined inline.

**Comment by jwetzell** [comment]
So basically just abstract the `data: { <whatever is here> }` out into a <resource>-data.model

**Comment by ethanmassie** [comment]
Yup. It might be useful if there is ever a situation where you just want to return the data without the wrapper object.

**Comment by jwetzell** [comment]
PR open for the Summary resource. Also converted to abstracting the `data: ` parts out

**Comment by ethanmassie** [comment]
I'm gonna go ahead and finish the study materials unless you've already started that.

**Comment by jwetzell** [comment]
Nope, all yours!

**Comment by ethanmassie** [comment]
Looks like we have everything done. Right?

**Comment by jwetzell** [comment]
Yes I believe so

**Comment by ethanmassie** [comment]
Cool, I'll close this issue then. Looks like we just need to go through and do some cleanup.
