### ISSUE TITLE
Creating review doesn't allow for subject_id

### ISSUE THREAD

**Issue by jwetzell** [ethanmassie/wanikani-api-ng#11]
The [create-review-request](https://github.com/ethanmassie/wanikani-api-ng/blob/master/projects/wanikani-api-ng/src/lib/models/review/create-review-request.model.ts) object doesn't allow for the subject_id. See [WaniKani docs ](https://docs.api.wanikani.com/20170710/?javascript#create-a-review) they allow either the assignment_id OR the subject_id (but not both) when creating a review.

**Comment by ethanmassie** [comment]
One solution is to have a validation function for checking that this interface is populated correctly. This is my proposed solution. I made assignment_id and subject_id optional and this function checks that their truthy values are not the same (essentially xor).
```
export function isValid(req: CreateReviewRequest): boolean {
  return !!req.assignment_id !== !!req.subject_id;
}
```

**Comment by jwetzell** [comment]
Yeah that seems to check out. I don't know how far we want to get into verifying that request parameters and things like that are correct as you could also add checking that `incorrect_meaning_answers` and `incorrect_reading_answers` are `>= 0` but again don't know how far down that road we'd want to go

**Comment by ethanmassie** [comment]
Nah, we can let their api handle that. I'm assuming they'll respond with an error.

**Comment by jwetzell** [comment]
Oh yeah they respond with something like "invalid record".
