### ISSUE TITLE
Subscription active property should be a boolean

### ISSUE THREAD

**Issue by jwetzell** [ethanmassie/wanikani-api-ng#17]
I believe the type for the `action `property in `wani-subscription.model.ts` should be `boolean`. 
See [API docs for the layout](https://docs.api.wanikani.com/20170710/#user-data-structure)

**Comment by ethanmassie** [comment]
Did you mean `active`?

**Comment by ethanmassie** [comment]
But yes, you're right. I'm going to fix this now.

**Comment by ethanmassie** [comment]
Fixed in [this commit](https://github.com/ethanmassie/wanikani-api-ng/commit/d68d6b4ca3e4b360cd4b2b25a2887a95068e195f)

**Comment by jwetzell** [comment]
yes meant active
